### PR TITLE
Build instructions + changes to actually allow building

### PR DESCRIPTION
**Pull request by sticks-stuff**
Also now includes glsc and LICENSE

### CODE REVIEW

**Comment by branpk** [comment]
Thanks for adding the build instructions! I think the LICENSE should be a separate PR though since there might be more discussion there.

I noticed you added imgui into requirements.txt, whereas the pipenv version uses my fork of imgui. (I should try to use the original repo now actually). Does the program actually work when you building like this?

**Comment by sticks-stuff** [comment]
Ted and I have both been able to build using the original version of imgui

**Comment by sticks-stuff** [comment]
As for the license, choosing to put glsc inside the repo would require licensing all of it under the same license as glsc if I'm not mistaken. IANAL though so maybe someone could shed more light on this. We can always remove glsc.exe from the repo and tell people to download it elsewhere in the build instructions.

**Comment by branpk** [comment]
Addressed in #7

**Pull request closed without merging**
